/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_broad_igv_d4_D4FileParser */

#ifndef _Included_org_broad_igv_d4_D4FileParser
#define _Included_org_broad_igv_d4_D4FileParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_broad_igv_d4_D4FileParser
 * Method:    d4_open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_broad_igv_d4_D4FileParser_d4_1open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_broad_igv_d4_D4FileParser
 * Method:    d4_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_broad_igv_d4_D4FileParser_d4_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_broad_igv_d4_D4FileParser
 * Method:    d4_chrom_name
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_broad_igv_d4_D4FileParser_d4_1chrom_1name
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_broad_igv_d4_D4FileParser
 * Method:    d4_run_stat
 * Signature: (JILjava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_org_broad_igv_d4_D4FileParser_d4_1run_1stat
  (JNIEnv *, jclass, jlong, jint, jstring, jint, jint, jint);

/*
 * Class:     org_broad_igv_d4_D4FileParser
 * Method:    d4_stat_size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_broad_igv_d4_D4FileParser_d4_1stat_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_broad_igv_d4_D4FileParser
 * Method:    d4_stat_get_value
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_org_broad_igv_d4_D4FileParser_d4_1stat_1get_1value
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_broad_igv_d4_D4FileParser
 * Method:    d4_stat_get_begin
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_broad_igv_d4_D4FileParser_d4_1stat_1get_1begin
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_broad_igv_d4_D4FileParser
 * Method:    d4_stat_get_end
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_broad_igv_d4_D4FileParser_d4_1stat_1get_1end
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_broad_igv_d4_D4FileParser
 * Method:    d4_stat_get_max
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_broad_igv_d4_D4FileParser_d4_1stat_1get_1max
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_broad_igv_d4_D4FileParser
 * Method:    d4_stat_get_min
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_broad_igv_d4_D4FileParser_d4_1stat_1get_1min
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_broad_igv_d4_D4FileParser
 * Method:    d4_stat_free
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_broad_igv_d4_D4FileParser_d4_1stat_1free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
