name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on:  macos-latest

    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '11'
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: cd d4lib && make
