name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on:  [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '11'
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build Rust
      run: cd d4lib && make
    - name: Build Java
      run: ./gradlew createDist
    - name: Prepare Artifact
      run: mv build/IGV-dist/ .
    - uses: actions/upload-artifact@v2
      with:
        name: IGV-D4
        path: IGV-dist/
